name             'cog_nginx'
maintainer       'Lauri Jesmin'
maintainer_email 'lauri.jesmin@cashongo.co.uk'
license          'All rights reserved'
description      'Installs NGINX'
long_description ''
version          '0.1.7'
supports 'centos', '~> 7.0'
supports 'redhat', '~> 7.0'

depends 'yum-epel',     '~> 0.6.0'
